keys:
  - &primary age10mfj8trak6n4dl5tpsf4jmjdu6z096zmqmurhcy424kw867g69cqysqn4t
  - &pex age124jxte5pvr4estavf2m5daweqczxkkff2dyvm3sgynac4r4cqcuqslxya8
creation_rules:
  - path_regex: secrets/.*\.sops$
    key_groups:
      - age:
          - *primary
          - *pex
